repos:
  # Basic code hygiene checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace          # Remove trailing whitespace
      - id: end-of-file-fixer            # Ensure newline at end of file
      - id: check-yaml                   # YAML syntax validation
      - id: check-merge-conflict         # Detect leftover merge conflict markers
      - id: check-added-large-files
        args: ['--maxkb=500']

  # Code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.10     # Set to project's Python version
        args: ['--line-length=88']       # Set line length as per Black's default

  # Import sorting with isort for consistency
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black']     # Align with Black's formatting style

  # Linting with flake8 for code quality
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--ignore=E203,W503']
        additional_dependencies:
          - flake8-bugbear==24.10.31     # Catch common Python pitfalls
          - flake8-comprehensions==3.13.0  # Encourage optimized comprehensions

  # Type checking with mypy for function annotations
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports     # Avoid errors for missing imports
          - --disallow-untyped-defs      # Enforce type annotations on functions
          - --strict                     # Enable all optional error checks

  # Security linting with Bandit for essential security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit

  # Spell checking with codespell for basic spelling mistakes in code comments
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --skip="*.pyc"                # Skip compiled Python files

  # Markdown formatting with Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.md$                     # Apply only to markdown files

  # markdownlint: Markdown linter
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        args: ['-r', '.mdlrc']
